/* node brand/tools/render-social.cjs REVIEW_DIR [CHROMIUM_EXECUTABLE] [SOURCE_DIR]
   Renders SVGs, checks actual font bounds and exports opaque 1280 × 640 PNGs. */
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{createHash}=require('node:crypto');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'../..'),out=process.argv[2],source=process.argv[4]||path.join(root,'brand/social');
if(!out)throw Error('Provide review output directory.');fs.mkdirSync(out,{recursive:true});
const m=JSON.parse(fs.readFileSync(path.join(source,'manifest.json'),'utf8'));const cards=m.cards.map(c=>({...c,svg:fs.readFileSync(path.join(source,c.file),'utf8')}));
const data=s=>'data:image/svg+xml;base64,'+Buffer.from(s).toString('base64');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const img=(c,w)=>`<img src="${data(c.svg)}" width="${w}" height="${w/2}" alt="${escape(c.name.replaceAll('\n',' '))}">`;
const fallback=s=>s.replace(/font-family="([^"]*)"/g,(_,f)=>`font-family="${f.includes('Georgia')?'serif':f.includes('Consolas')?'monospace':'sans-serif'}"`);
(async()=>{const browser=await chromium.launch({headless:true,...(process.argv[3]?{executablePath:process.argv[3]}:{})});try{
 const page=await browser.newPage({viewport:{width:1384,height:1100},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());const checks=[],pngHashes={};
 for(const c of cards){
  for(const mode of ['preferred','generic-fallback']){
   await page.setContent(`<style>body{margin:0}</style>${mode==='preferred'?c.svg:fallback(c.svg)}`);await page.evaluate(()=>document.fonts.ready);
   const result=await page.evaluate(()=>{const text=[...document.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {text:t.textContent,x:b.x,y:b.y,width:b.width,height:b.height,safe:b.x>=63.5&&b.y>=64&&b.x+b.width<=1216.5&&b.y+b.height<=576};});const box=id=>{const b=document.getElementById(id).getBBox();return {x:b.x,y:b.y,w:b.width,h:b.height};};const title=box('project-name'),desc=box('project-descriptor'),study=box('project-study');return {text,title,desc,study,slots:title.x+title.w<=792&&desc.x+desc.w<=792&&title.y+title.h+12<=desc.y&&desc.y+desc.h<492&&(study.w===0||(study.x>=864&&study.x+study.w<=1216.5))};});
   if(!result.slots||result.text.some(t=>!t.safe))throw Error(c.id+' '+mode+' bounds failed '+JSON.stringify(result));
   checks.push({id:c.id,mode,...result});
  }
  await page.setContent(`<style>body{margin:0}</style>${img(c,1280)}`);await page.locator('img').evaluate(n=>n.decode());
  const png=await page.locator('img').evaluate(n=>{const c=document.createElement('canvas');c.width=1280;c.height=640;const ctx=c.getContext('2d',{alpha:false});ctx.drawImage(n,0,0);return c.toDataURL('image/png').split(',')[1];});
  const dest=path.join(c.id==='social-preview-template'?out:source,c.id+'.png');fs.writeFileSync(dest,Buffer.from(png,'base64'));pngHashes[c.id+'.png']=createHash('sha256').update(fs.readFileSync(dest)).digest('hex');if(fs.statSync(dest).size>=1000000)throw Error('PNG exceeds 1 MB '+dest);
  for(const w of [640,320]){await page.setContent(`<style>body{margin:0}</style>${img(c,w)}`);await page.locator('img').evaluate(n=>n.decode());await page.locator('img').screenshot({path:path.join(out,c.id+'-'+w+'.png')});}
 }
 const examples=cards.filter(c=>c.id!=='social-preview-template'),template=cards[0];
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><title>M4 · Repository visual system</title><style>*{box-sizing:border-box}body{margin:0;background:#F5F0E6;color:#102A36;font:16px 'Segoe UI',Arial,sans-serif}main{width:1384px;padding:36px 40px}h1{font:normal 40px Georgia,serif;margin:10px 0}h2{font:normal 26px Georgia,serif;margin:12px 0}p{font-size:14px;line-height:1.5;color:#52616A}.eyebrow{font-size:11px;letter-spacing:2px}img{display:block}.anatomy{display:flex;align-items:center;gap:24px;border-top:1px solid #C7CBC5;border-bottom:1px solid #C7CBC5;padding:24px 0;margin:28px 0}.anatomy aside{flex:1}.anatomy aside p{font-size:13px}.grid{display:grid;grid-template-columns:repeat(2,640px);gap:24px}.card p{margin-top:10px}.small{display:flex;gap:8px}.small figure{margin:0}.small figcaption{font-size:12px;margin-top:8px}.fixed{color:#52616A}.variable{color:#8c6022}.footer{border-top:1px solid #C7CBC5;margin-top:28px;padding-top:16px}</style><main><div class="eyebrow">PATITOS FORTUNE / M4 / VISUAL REVIEW</div><h1>Different experiments. One laboratory.</h1><p>A specimen-label system: project-first typography, one study illustration and a consistent colorful lab signature.</p><section class="anatomy"><div>${img(template,864)}</div><aside><h2>Template anatomy</h2><p class="fixed"><b>FIXED</b><br>1280 × 640 canvas<br>64 px essential-content margin<br>Editorial title + native label roles<br>Divided study field + double rules<br>Colorful duck and lab attribution at foot</p><p class="variable"><b>CONTROLLED VARIABLES</b><br>Project title and descriptor<br>Category / optional catalogue ID<br>One palette accent<br>Paper or Ink field<br>Project diagram / illustration</p><p>Project identity leads. Institutional detail stays secondary. Decorative frames sit outside the 64 px safe area.</p></aside></section><h2>Four fictional specimens · 640 × 320</h2><p>Half-resolution checks below are actual browser pixels at 100% view. Full exports are exactly 1280 × 640.</p><section class="grid">${examples.map(c=>`<div class="card">${img(c,640)}<p>${c.theme==='ink'?'Ink / reverse facets':'Paper / primary facets'} · ${c.accent} · ${c.motif}</p></div>`).join('')}</section><h2>Small preview check · 320 × 160</h2><p>Project name and motif carry recognition. Descriptor and specimen metadata are secondary at this scale.</p><section class="small">${examples.map(c=>`<figure>${img(c,320)}<figcaption>${escape(c.name.replaceAll('\n',' '))}</figcaption></figure>`).join('')}</section><div class="footer"><p>All names and example descriptors are fictional. No repository rollout or uploads. M1–M3 remain unchanged; ${m.status==='approved'?'M4 system approved; no rollout or uploads.':'Custom project cards await visual review.'} No commits or pushes.</p></div></main></html>`;
 const file=path.resolve(out,'m4-social-review.html');fs.writeFileSync(file,html);await page.goto(pathToFileURL(file).href);await page.locator('img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode())));await page.locator('main').screenshot({path:path.join(out,'m4-social-review.png')});
 fs.writeFileSync(path.join(out,'social-render-report.json'),JSON.stringify({browser:await browser.version(),errors,checks,pngHashes,sourceHashes:Object.fromEntries(cards.map(c=>[c.file,createHash('sha256').update(c.svg).digest('hex')]))},null,2)+'\n');
 if(errors.length)throw Error(errors.join('\n'));console.log('Exported cards; preferred/generic font bounds, safe margins, slots, PNG budget and 640/320 px renders PASS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
